name: g_diffuser
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit
  - pytorch
  - torchvision
  - numpy 
  - pip:
    - docker
    - pyyaml
    - opencv-python
    - aiofiles
    - discord
    - wsgicors
    - service_identity
    - grpcio
    - google-api-python-client
    - git+https://github.com/huggingface/diffusers.git